export const SUPABASE_URL = 'https://dyqegdspimnnfkglwmmw.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5cWVnZHNwaW1ubmZrZ2x3bW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTAyNjQsImV4cCI6MjA3MjY2NjI2NH0.5pE_TVm7mL1BRjGilLHFJoGIQWkiiXAWQ5WRhgIOdLs';
